// <auto-generated />
namespace GameStoredTwo.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class next52 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(next52));
        
        string IMigrationMetadata.Id
        {
            get { return "202012011959297_next52"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
